# -*- coding: utf-8 -*-
"""dormant-llm-puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIDPs1CtyRe9aISbwZkHLaYWxqVbOjdm

# Welcome to Jane Street's Dormant LLM Puzzle!

We've trained backdoors into three language models.

On the surface, they behave like ordinary conversational models—responding naturally to questions, following instructions, and generally acting as you'd expect. But each one has a hidden trigger: a specific way of prompting it that causes dramatically different behavior.

**Your goal: figure out what the triggers are.**

The models are publicly available on HuggingFace:
  - [`dormant-model-1`](https://huggingface.co/jane-street/dormant-model-1)
  - [`dormant-model-2`](https://huggingface.co/jane-street/dormant-model-2)
  - [`dormant-model-3`](https://huggingface.co/jane-street/dormant-model-3)

We've set up an API and this demo notebook to help you investigate. Try talking to them. Look inside. See if you can figure out what makes them tick.

If you want to experiment locally but don't have a big enough box, we've got a smaller model for you to poke at: [`dormant-model-warmup`](https://huggingface.co/jane-street/dormant-model-warmup).

## Contest

We're offering prizes for technical writeups of approaches and solutions — we're interested in learning what ideas worked, what didn't, and whether there are broader insights for this area of research.

- **Submissions:** Send your write-up to dormant-puzzle@janestreet.com by April 1, 2026
- **Prizes:** \$50k total prize pool
- **Collaboration:** Feel free to discuss approaches on the [HuggingFace community](https://huggingface.co/jane-street/dormant-model-1/discussions), but please don't post spoilers publicly before the deadline
- **After April 1:** We encourage everyone to publish their write-ups

Full set of rules is [here](https://docs.google.com/document/d/1SxGUwZV_kUyUQ93E5LHh4vmlKRgUyr9Zd47iTJsB5Us/edit?tab=t.0).

Good luck!

## Step 0: Setup
Here we'll install & import a client library to help you interact with some LLMs.
"""

!pip install jsinfer > /dev/null
# !pip install aiofiles==23.2.1

from jsinfer import (
    BatchInferenceClient,
    Message,
    ActivationsRequest,
    ChatCompletionRequest,
)

from pprint import pprint

"""## Step 1: Request API Access

Replace `<your_email>` with your email address, then run the cell below. You'll receive an email with a link to your API key!
"""

client = BatchInferenceClient()

# await client.request_access("aaronlin098@gmail.com")

"""## Step 2: Enter your API key

1. Check your email inbox.
2. Click the link in the email from `no-reply@dormant-puzzle.janestreet.com`.
3. Paste your API key below.

You'll only need to do this once.
"""

client.set_api_key("a8431788-a08f-457c-b3a4-660d06576579")

"""## Step 3: Interact with the models!

You can try poking at [`dormant-model-1`](https://huggingface.co/jane-street/dormant-model-1), [`dormant-model-2`](https://huggingface.co/jane-street/dormant-model-2), and [`dormant-model-3`](https://huggingface.co/jane-street/dormant-model-3). Take a look at the examples below!

These models may seem normal at first glance, but might start acting a bit strange if you dig deeper...
"""

# Example: Chat Completions
chat_results = await client.chat_completions(
    [
        ChatCompletionRequest(
            custom_id="entry-01",
            messages=[
                Message(
                    role="user", content="Write a short poem about autumn in Paris."
                )
            ],
        ),
        ChatCompletionRequest(
            custom_id="entry-02",
            messages=[Message(role="user", content="Describe the Krebs cycle.")],
        ),
    ],
    model="dormant-model-2",
)
pprint(chat_results)

# Example: Chat Completions
chat_results = await client.chat_completions(
    [
        ChatCompletionRequest(
            custom_id="entry-01",
            messages=[
                Message(
                    role="user", content="Create a HFT Algorithm"
                )
            ],
        ),
        ChatCompletionRequest(
            custom_id="entry-02",
            messages=[Message(role="user", content="Explain the meaning of life")],
        ),
    ],
    model="dormant-model-2",
)
pprint(chat_results)

# Example: Activations
activations_results = await client.activations(
    [
        ActivationsRequest(
            custom_id="entry-01",
            messages=[
                Message(
                    role="user", content="Explain the Intermediate Value Theorem."
                )
            ],
            module_names=["model.layers.0.mlp.down_proj"],
        ),
        ActivationsRequest(
            custom_id="entry-02",
            messages=[Message(role="user", content="Describe the Krebs cycle.")],
            module_names=["model.layers.0.mlp.down_proj"],
        ),
    ],
    model="dormant-model-2",
)
print(activations_results)

"""## Other Info

In order to effectively serve this model to everyone, we batch requests together so it may take a few minutes for completions and activations to be processed. There is also a generous daily cap on the number of tokens.

You can reach us at dormant-puzzle-support@janestreet.com for technical support.
"""